"""add invitation system

Revision ID: 8e021722d828
Revises: cfbeca6d49f4
Create Date: 2026-06-30 16:39:15.870809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e021722d828'
down_revision: Union[str, Sequence[str], None] = 'cfbeca6d49f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.Column('invited_by_id', sa.UUID(), nullable=False),
    sa.Column('invited_user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REVOKED', name='invitationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invited_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('board_id', 'invited_user_id', name='uq_board_invited_user'),
    sa.UniqueConstraint('token')
    )
    op.drop_constraint(op.f('boards_invitation_token_key'), 'boards', type_='unique')
    op.drop_column('boards', 'invitation_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('invitation_token', sa.UUID(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('boards_invitation_token_key'), 'boards', ['invitation_token'], postgresql_nulls_not_distinct=False)
    op.drop_table('invitations')
    # ### end Alembic commands ###
