"""remove invitation unique constraint

Revision ID: f3cee37c9ad4
Revises: 8e021722d828
Create Date: 2026-06-30 16:47:04.858725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3cee37c9ad4'
down_revision: Union[str, Sequence[str], None] = '8e021722d828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_board_invited_user'), 'invitations', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_board_invited_user'), 'invitations', ['board_id', 'invited_user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
